services:
  # ====================================
  # Frontend service using Nginx to serve the built assets from Vite.
  # ====================================
  tri-app:
    build:
      context: ./frontend/triplydev
      dockerfile: ./docker/production/nginx/Dockerfile
      target: production
    container_name: tri-app
    restart: unless-stopped
    env_file:
      - ./frontend/triplydev/.env
    networks:
      - triply-production
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.tri-front.rule=Host(`triply.ovh`)"
      - "traefik.http.routers.tri-front.entrypoints=websecure"
      - "traefik.http.routers.tri-front.tls.certresolver=myresolver"
      - "traefik.http.services.tri-front.loadbalancer.server.port=3000"

  tri-api:
    build:
      context: ./backend
      dockerfile: ./docker/production/nginx/Dockerfile
    container_name: tri-api
    restart: unless-stopped # Automatically restart unless the service is explicitly stopped
    volumes:
      # Mount the 'tri-storage-production' volume to '/var/www/storage' inside the container.
      # -----------------------------------------------------------
      # This volume stores persistent data like uploaded files and cache.
      # The ':ro' option mounts it as read-only in the 'api' service because Nginx only needs to read these files.
      # The 'php-fpm' service mounts the same volume without ':ro' to allow write operations.
      # -----------------------------------------------------------
      - tri-storage-production:/var/www/storage:ro
    networks:
      - triply-production
    depends_on:
      tri-php-fpm:
        condition: service_healthy  # Wait for tri-php-fpm health check

  tri-php-fpm:
    # For the php-fpm service, we will create a custom image to install the necessary PHP extensions and setup proper permissions.
    build:
      context: ./backend
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
    container_name: tri-php-fpm
    restart: unless-stopped
    volumes:
      - tri-public-assets:/var/www/public/build  # Mount built public assets to ensure the manifest.json and hashed files match between Nginx and PHP-FPM
      - tri-storage-production:/var/www/storage  # Mount the storage volume
    env_file:
      - ./backend/.env
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: tri-postgres
      DB_PORT: 5432
    networks:
      - triply-production
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    # The 'depends_on' attribute with 'condition: service_healthy' ensures that
    # this service will not start until the 'pgsql' service passes its health check.
    # This prevents the application from trying to connect to the database before it's ready.
    depends_on:
      tri-postgres:
        condition: service_healthy

  tri-postgres:
    image: postgres:16
    restart: unless-stopped
    user: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - tri-postgres-data:/var/lib/postgresql/data
    networks:
      - triply-production
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:alpine
    container_name: tri-redis
    restart: unless-stopped  # Automatically restart unless the service is explicitly stopped
    networks:
      - triply-production
    # Health check for Redis
    # -----------------------------------------------------------
    # Checks if Redis is responding to the 'PING' command.
    # This ensures that the service is not only running but also operational.
    # -----------------------------------------------------------
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  tri-pgadmin:
    image: dpage/pgadmin4
    environment:
      PMA_HOST: tri-postgres
      POSTGRES_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    networks:
      - triply-production
    depends_on:
      tri-postgres:
        condition: service_healthy # Wait for postgres to be healthy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.tri-pgadmin.rule=Host(`bdmenacesatanique.triply.ovh`)"
      - "traefik.http.routers.tri-pgadmin.entrypoints=websecure"
      - "traefik.http.routers.tri-pgadmin.tls.certresolver=myresolver"
      - "traefik.http.services.tri-pgadmin.loadbalancer.server.port=80"

networks:
  # Attach the service to the 'laravel' network.
  # -----------------------------------------------------------
  # This custom network allows all services within it to communicate using their service names as hostnames.
  # For example, 'php-fpm' can connect to 'pgsql' by using 'tri-postgres' as the hostname.
  # -----------------------------------------------------------
  triply-production:
    name: triply-production
  web:
    external: true  # Use the existing 'web' network created by Traefik

volumes:
  tri-postgres-data:
  tri-storage-production:
  tri-public-assets: