services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./backend:/app
    ports:
      - "8000:80"
    depends_on:
      - db

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    volumes:
#      - ./frontend:/app
#    ports:
#      - "5173:5173"
#    env_file:
#      - ./frontend/.env.docker
#    command: sh -c "npm install --save-dev @rollup/rollup-linux-x64-gnu && npm run dev -- --host 0.0.0.0"

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: backend
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "contact@triply.ovh"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
      - ./pgadmin/pgpass:/pgpass:ro
    depends_on:
      - db

volumes:
  pg_data:
